
# eureka enabled
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    healthcheck:
      enabled: true  
    serviceUrl:
      defaultZone: http://localhost:10010/eureka/     

management:
  security:
    enabled: false
