
# eureka enabled
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    healthcheck:
      enabled: true  
    serviceUrl:
      defaultZone: http://localhost:10013/eureka/     

management:
  security:
    enabled: false

# zipkin
spring:
  zipkin:
    baseUrl: http://192.168.56.101:10014/
