
# log level
logging:
  file: ___bootadmin.log
  level:
    root: DEBUG    

# ports
server:
  port: 10012

# management
management:
  security:
    enabled: false
  
# actuator endpoints
endpoints:
  enabled: true
  sensitive: false
  shutdown:
    enabled: true
    sensitive: false 

# endpoints
spring:
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
