
# log level
logging:
  file: ___hystrix.log
  level:
    root: INFO    

# ports
server:
  port: 10015

# management
management:
  security:
    enabled: false  

# actuator endpoints
endpoints:
  enabled: true
  sensitive: false
  shutdown:
    enabled: true
    sensitive: false 

# turbine
turbine:
  aggregator:
    clusterConfig: ZUUL
  appConfig: ZUUL
