
# log level
logging:
  file: ___eureka.log
  level:
    root: DEBUG

# port
server:
  port: 10013    

# actuator endpoints
endpoints:
  enabled: true
  sensitive: false
  shutdown:
    enabled: true
    sensitive: false 
