# eureka enabled
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    # registerWithEureka: false
    # fetchRegistry: false
    healthcheck:
      enabled: true  
    serviceUrl:
      defaultZone: http://192.168.56.101:10013/eureka/
