
# log level
logging:
  file: ___eureka.log
  level:
    root: DEBUG

# app name
spring:
  application:
    name: eureka

# port
server:
  port: 10010 
      
# eureka enabled
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    # registerWithEureka: false
    # fetchRegistry: false
    healthcheck:
      enabled: true  
    serviceUrl:
      defaultZone: http://localhost:10010/eureka/       

# actuator endpoints
endpoints:
  enabled: true
  sensitive: false
  shutdown:
    enabled: true
    sensitive: false 
