/**
 * Prueba Concepto API RESTful
 * Prueba de concepto de un API RESTful.
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: jotasumin@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface AddPersonaBody {
    id?: string;

    nombre: string;

    profesion: string;

}
