swagger: '2.0'
info:
  version: '1.0'
  title: Hola Mundo API
  description: Probando swagger con Hola Mundo API
host: 'localhost:8080'
basePath: /v1
schemes:
  - http
  - https
paths:
  /helloworld:
    get:
      summary: Devuelve un Hello World
      description: Endpoint que devuelve un Hello World
      responses:
        '200':
          description: Response OK
          schema:
            type: string
            example: Hello World
  /holamundo:
    get:
      summary: Devuelve un Hola Mundo
      description: Endpoint que devuelve un Hola Mundo
      responses:
        '200':
          description: Response OK
          schema:
            $ref: '#/definitions/Saludo'
definitions:
  Saludo:
    properties:
      palabra01:
        type: string
        example: Hola
      palabra02:
        type: string
        example: Mundo
    required:
      - palabra01
      - palabra02
