print("*********************************************")
print("*                                           *")
print("*  WARNING: Es necesario ejecutar los tests *")
print("*           unitarios de angular            *")
print("*                                           *")
print("*********************************************")
