/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-07-17T11:08:28.154Z")

@Api(value = "helloworld", description = "the helloworld API")
public interface HelloworldApi
{
	@CrossOrigin(origins = "*")
	@ApiOperation(value = "Devuelve un Hello World", notes = "Endpoint que devuelve un Hello World", response = String.class, tags = {})
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Response OK", response = String.class) })
	@RequestMapping(value = "/helloworld", method = RequestMethod.GET)
	ResponseEntity<String> helloworldGet();
}
