# eureka enabled
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    healthcheck:
      enabled: true  
    serviceUrl:
      defaultZone: http://192.168.56.101:10013/eureka/     

# routes
zuul:
  routes:
    persona:
      path: /v1/**
      stripPrefix: true
      serviceId: PERSONAAPI
