
# log level
logging:
  file: ___zuul.log
  level:
    root: DEBUG    

# ports
server:
  port: 10008

# management
management:
  security:
    enabled: false  

# actuator endpoints
endpoints:
  enabled: true
  sensitive: false
  shutdown:
    enabled: true
    sensitive: false 
