
# log level
logging:
  file: zuul.log
  level:
    root: DEBUG    

# ports
server:
  port: 10008

# app name
spring:
  application:
    name: zuul

# actuator endpoints
endpoints:
  enabled: true
  sensitive: false
  shutdown:
    enabled: true
    sensitive: false 
