
# eureka enabled
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:10010/eureka/    

# routes
zuul:
  routes:
    persona:
      path: /v1/persona/**
      stripPrefix: false
      url: http://localhost:10006
