
# eureka enabled
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    healthcheck:
      enabled: true  
    serviceUrl:
      defaultZone: http://localhost:10010/eureka/     

# routes
zuul:
  routes:
    persona:
      path: /v1/persona/**
      stripPrefix: false
      serviceId: PERSONAAPI
