# eureka enabled
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    healthcheck:
      enabled: true  
    serviceUrl:
      defaultZone: http://localhost:10013/eureka/     

# routes
zuul:
  routes:
    persona:
      path: /v1/**
      stripPrefix: true
      serviceId: PERSONAAPI

# zipkin
spring:
  zipkin:
    baseUrl: http://localhost:10014/
      