
# eureka enabled
eureka:
  instance:
    instanceId: personaapi.${random.value}
  client:
    healthcheck:
      enabled: true  
    serviceUrl:
      defaultZone: http://192.168.56.101:10013/eureka/    

# mongodb
spring:
  data:
    mongodb:
      host: 192.168.56.101
      port: 27017
      database: personas
