
# eureka enabled
eureka:
  instance:
    instanceId: personaapi.${random.value}
  client:
    healthcheck:
      enabled: true  
    serviceUrl:
      defaultZone: http://localhost:10013/eureka/    

# mongodb
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: personas
