
# ports
server:
  port: 0

# eureka enabled
eureka:
  instance:
    statusPageUrlPath: /v1/info
    healthCheckUrlPath: /v1/health
    instanceId: personaapi.${random.value}
  client:
    healthcheck:
      enabled: true  
    serviceUrl:
      defaultZone: http://localhost:10010/eureka/    
