
# log level
logging:
  file: ___personaapi.${random.value}.log
  level:
    root: DEBUG    

# ports
server:
  port: 0

# management
management:
  security:
    enabled: false

# actuator endpoints
endpoints:
  enabled: true
  sensitive: false
  shutdown:
    enabled: true
    sensitive: false 
