
# log level
logging:
  file: ___personaapi.${random.value}.log
  level:
    root: DEBUG    

# context path
# server:
#  contextPath: /v1

# app config
spring:
  application:
    name: personaapi

# actuator endpoints
endpoints:
  enabled: true
  sensitive: false
  shutdown:
    enabled: true
    sensitive: false 
