
# eureka enabled
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health  
    instanceId: personaapi.${random.value}
  client:
    healthcheck:
      enabled: true  
    serviceUrl:
      defaultZone: http://192.168.56.101:10013/eureka/    

# spring
spring:
  zipkin:
    baseUrl: http://192.168.56.101:10014/
  data:
    mongodb:
      host: 192.168.56.101
      port: 27017
      database: personas
