
# log level
logging:
  file: ___personaapi.${random.value}.log
  level:
    root: DEBUG    


# ports
server:
  port: 0

# context path
# server:
#  contextPath: /v1

# actuator endpoints
endpoints:
  enabled: true
  sensitive: false
  shutdown:
    enabled: true
    sensitive: false 
