swagger: '2.0'
info:
  version: '1.0'
  title: Hola Mundo API
paths:
  /holamundo:
    get:
      description: Devuelve un Hola Mundo !!!
      responses:
        '200':
          description: Response OK
          schema:
            type: string
          examples:
            response: Hola Mundo !!!
